version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        links:
            - app
        environment:
            DOMAIN: ${DOMAIN}
            DOC_ROOT: '/var/www/html/${DOMAIN}/web'
        volumes:
            - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
            - ${SRC_DIR}:/var/www/html/${DOMAIN} 
        command: /bin/sh -c "envsubst '$$DOMAIN$$DOC_ROOT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    app:
        build: php-fpm
        links:
            - db
        volumes:
            - ${SRC_DIR}:/var/www/html/${DOMAIN}
    data:
        image: busybox
        volumes:
            - ./misc/data:/var/lib/mysql
    db:
        build: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"
        volumes_from:
            - data
