version: '3'

services:
  nginx:
    image: nginx:1.11
    ports:
      - '8000:80'
    links:
      - app
    environment:
      DOMAIN: ${DOMAIN}
      DOC_ROOT: /var/www/html/${DOMAIN}/${PUBLIC_DIR}
    volumes:
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
      - ${SRC_DIR}:/var/www/html/${DOMAIN} 
    command: /bin/sh -c "envsubst '$$DOMAIN$$DOC_ROOT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  app:
    build: php-fpm
    links:
      - db
      - redis
    volumes:
      - ${SRC_DIR}:/var/www/html/${DOMAIN}
    working_dir: /var/www/html
  php-cli:
    build: php-cli
    volumes:
      - ${SRC_DIR}:/var/www/html/${DOMAIN}
    working_dir: /var/www/html/${DOMAIN}
  composer:
    image: composer
    volumes:
      - ${SRC_DIR}:/app
      - ./composer/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
  db:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./misc/data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
